// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnIW9A-Dvjr2qs0QFhwUkuJpfq2rEA0zg',
    appId: '1:885324992533:web:379d5c7dc1e8d73d6e7e1c',
    messagingSenderId: '885324992533',
    projectId: 'movie-recommender-app-912d2',
    authDomain: 'movie-recommender-app-912d2.firebaseapp.com',
    storageBucket: 'movie-recommender-app-912d2.firebasestorage.app',
    measurementId: 'G-BXPXEV9RHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwhv01zTY2p03MY_PhS_mYceMC69NnQMI',
    appId: '1:885324992533:android:be988bb11ced03fd6e7e1c',
    messagingSenderId: '885324992533',
    projectId: 'movie-recommender-app-912d2',
    storageBucket: 'movie-recommender-app-912d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVo305DfitWsUW3tiFL7I6vGmSumfEu-M',
    appId: '1:885324992533:ios:2459c52c4f645c026e7e1c',
    messagingSenderId: '885324992533',
    projectId: 'movie-recommender-app-912d2',
    storageBucket: 'movie-recommender-app-912d2.firebasestorage.app',
    iosClientId: '885324992533-eb0flue93d503onmmmt8ptir67n22d9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMovieRecommenderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVo305DfitWsUW3tiFL7I6vGmSumfEu-M',
    appId: '1:885324992533:ios:2459c52c4f645c026e7e1c',
    messagingSenderId: '885324992533',
    projectId: 'movie-recommender-app-912d2',
    storageBucket: 'movie-recommender-app-912d2.firebasestorage.app',
    iosClientId: '885324992533-eb0flue93d503onmmmt8ptir67n22d9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMovieRecommenderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnIW9A-Dvjr2qs0QFhwUkuJpfq2rEA0zg',
    appId: '1:885324992533:web:6edd5a1cf32d3c456e7e1c',
    messagingSenderId: '885324992533',
    projectId: 'movie-recommender-app-912d2',
    authDomain: 'movie-recommender-app-912d2.firebaseapp.com',
    storageBucket: 'movie-recommender-app-912d2.firebasestorage.app',
    measurementId: 'G-8PHD9SQ662',
  );
}
